[phys]
Re = 628.3185307179584 # Reynolds number
forcing = "kolmogorov" 
# forcings: "none", "kolmogorov" (sine), "waleffe" (cosine + Ry symmetry)

[geo]
Lx = 4.0
Lz = 2.0
# ... in units where Ly = 4.0 is fixed.

[res]
Nx = 48
Ny = 48
Nz = 24
# Nx Ny and Nz are the number of Fourier modes
# (= # of grid points) *before* 3/2 oversampling 
# to delias the 2nd order nonlinearity

[init]
start_from_laminar = false
snapshot = "/mnt/c/Users/gokhan/Seafile/projects/dnsjax/invariants/01/u0.npz"
t0 = 0 # Initial time
it0 = 0 # Initial discrete time

[outs]
it_stats = 20 # How often to compute stats (in number of time steps)

[step]
dt = 0.02
implicitness = 0.5
corrector_tolerance = 1e-5
max_corrector_iterations = 10

[stop]
max_sim_time = 35.8

[debug]
time_functions = false
